# Generated by Django 2.1.4 on 2018-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=3)),
                ('info', models.TextField()),
                ('image', models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='assets/episodes/images/')),
                ('audio', models.FileField(default='assets/not-found.mp3', max_length=500, upload_to='assets/episodes/audio/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
