# Generated by Django 2.1.4 on 2018-12-23 17:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(default='assets/not-found.mp3', max_length=500, upload_to='episodes/audio/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(default='assets/not-found.jpg', max_length=500, upload_to='episodes/images/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
