# Generated by Django 2.1.4 on 2018-12-23 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_remove_episode_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='info',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
