# Generated by Django 2.1.4 on 2019-05-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_episode_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
