# Generated by Django 2.1.4 on 2018-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
