# Generated by Django 2.1.4 on 2018-12-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriptionrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionrequest',
            options={'ordering': ['email']},
        ),
    ]
