# Generated by Django 2.1.4 on 2018-12-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20181216_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='token',
            field=models.TextField(default='', max_length=125),
            preserve_default=False,
        ),
    ]
